/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *adminViewCurrentWineWineries;
    QWidget *mainMenu;
    QPushButton *push_button_viewListOfWineries;
    QPushButton *pushButton_planTrip;
    QPushButton *pushButton_tourAndPurchase;
    QPushButton *pushButton_Quit;
    QPushButton *pushButton_Admin;
    QLabel *label_mainTitle;
    QWidget *viewListOfWineries;
    QPushButton *pushButton_back_viewList;
    QPushButton *pushButton_viewCurrentList;
    QPushButton *pushButton_viewWines;
    QPushButton *pushButton_3;
    QPushButton *pushButton_10;
    QLabel *label_secondInViewList;
    QLabel *label_ViewListTitle;
    QLabel *label_Excellence;
    QPushButton *pushButton_viewDistanceList;
    QWidget *viewDistances;
    QTableWidget *distanceTable;
    QPushButton *backButtonViewDistance;
    QWidget *viewWines;
    QListWidget *list_wineList;
    QPushButton *pushButton_backViewWines;
    QLabel *viewWines_2;
    QLabel *label_featuredWines;
    QWidget *page_AboutTheVilla;
    QLabel *label_AboutTheVilla;
    QTextBrowser *textBrowser;
    QPushButton *pushButton_backAboutVilla;
    QLabel *label_AboutVilla2;
    QLabel *label_AboutVilla3;
    QLabel *label_AboutVIllaTItle;
    QPushButton *pushButton_website;
    QWidget *planATrip;
    QPushButton *pushButton_backPlanTrip;
    QLabel *label_planATrip;
    QPushButton *pushButton_;
    QPushButton *pushButton_shortestTrip;
    QPushButton *pushButton_visitAll;
    QWidget *page_finalVisitAll;
    QListWidget *list_visitAll;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QLabel *label_3;
    QLabel *label_distance_VisitAll;
    QLabel *visitAllTitle;
    QLabel *label_19;
    QWidget *page_shortestTrip;
    QPushButton *pushButton_5;
    QLineEdit *lineEdit_numberOfWineries;
    QLabel *label_15;
    QPushButton *pushButton_shortestTrip_next;
    QLabel *label_promptForWineries;
    QWidget *page_shortestTripPage2;
    QPushButton *pushButton_shortestTripPage2_back;
    QListWidget *list_customTripPage2;
    QPushButton *pushButton_9;
    QLabel *title_1;
    QWidget *page_shortestTripPage3;
    QListWidget *list_finalListShortestTrip;
    QLabel *label_2;
    QPushButton *pushButton_6;
    QPushButton *pushButton_15;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *distanceShortestTrip;
    QWidget *page_customTrip;
    QListWidget *list_customTrip;
    QPushButton *pushButton_next;
    QPushButton *pushButton_customTrip_back;
    QLabel *customTrip_title_1;
    QWidget *page_customTrip_final;
    QListWidget *list_FinalListCustomTrip;
    QPushButton *pushButton_shopForWines;
    QPushButton *push_button_customTrip_Done;
    QLabel *label_CustomTrip_Title;
    QLabel *label_16;
    QLabel *thankYou;
    QLabel *distanceCustomFinal;
    QWidget *tourWineriesAndPurchase;
    QPushButton *pushButton_backTourAndPurchase;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *label_20;
    QWidget *adminLogin;
    QLineEdit *lineEdit_username;
    QLineEdit *lineEdit_password;
    QLabel *label_5;
    QLabel *label_6;
    QPushButton *pushButton_8;
    QPushButton *pushButton_adminLogin;
    QLabel *label_AdminLogin;
    QWidget *afterAdminLogin;
    QPushButton *pushButton_adminLogout;
    QLabel *label_8;
    QPushButton *pushButton_4;
    QPushButton *pushButton_modifyWine;
    QLabel *label_titleAdminFunctions;
    QPushButton *pushButton_14;
    QWidget *page_addWineryInAdmin;
    QPushButton *pushButton_viewCurrentLists_addWinery;
    QLabel *label_CVLogoAdmin;
    QLabel *label_Add_winery_title;
    QPushButton *pushButton_11;
    QPushButton *pushButton_backAddWinery;
    QWidget *page_addWineryPage;
    QPushButton *addWineryOK;
    QPushButton *addWineryCancel;
    QWidget *page_AdminListVIew;
    QListWidget *listWidget_adminViewWIne;
    QListWidget *listWidget_adminViewWineries;
    QPushButton *pushButton_backInAdminList;
    QWidget *page_4;
    QWidget *page_ViewCurrentLists;
    QListWidget *list_currentWines;
    QListWidget *list_currentWineries;
    QLabel *label;
    QLabel *label_4;
    QPushButton *pushButton_backViewCurrentLists;
    QWidget *viewCurrentList_childOViewList;
    QPushButton *pushButton_backInListView;
    QListWidget *wineryList;
    QLabel *label_temp;
    QLabel *label_picture;
    QWidget *page_wineOptionsAdmin;
    QLabel *label_CVLogoAdmin_2;
    QPushButton *pushButton_back_wineOptions;
    QFrame *frame_6;
    QLabel *label_wineOptions;
    QPushButton *pushButton_addWine_wineOptions;
    QPushButton *pushButton_editWine_wineOptions;
    QWidget *page_addWine_wineOptionsAdmin;
    QFrame *frame;
    QComboBox *comboBox_selectWinery_addWine;
    QLabel *label_10;
    QFrame *frame_2;
    QLabel *label_9;
    QTextBrowser *textBrowser_viewCurrent_addWine;
    QFrame *frame_3;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEdit_wineName_addWine;
    QLineEdit *lineEdit_wineYear_addWine;
    QLineEdit *lineEdit_winePrice_addWine;
    QPushButton *pushButton_confirmAdd_addWine;
    QPushButton *pushButton_back_addWine;
    QWidget *page_editWine_wineOptionsAdmin;
    QPushButton *pushButton__back_editWine;
    QPushButton *pushButton_apply_editWine;
    QFrame *frame_4;
    QComboBox *comboBox_selectWinery_editWine;
    QLabel *label_selectWinery_editWine;
    QFrame *frame_5;
    QLabel *label_tableEdit_editWine;
    QTableWidget *tableWidget_editWine;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(634, 546);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        adminViewCurrentWineWineries = new QStackedWidget(centralWidget);
        adminViewCurrentWineWineries->setObjectName(QStringLiteral("adminViewCurrentWineWineries"));
        adminViewCurrentWineWineries->setGeometry(QRect(10, 10, 611, 461));
        mainMenu = new QWidget();
        mainMenu->setObjectName(QStringLiteral("mainMenu"));
        push_button_viewListOfWineries = new QPushButton(mainMenu);
        push_button_viewListOfWineries->setObjectName(QStringLiteral("push_button_viewListOfWineries"));
        push_button_viewListOfWineries->setGeometry(QRect(190, 190, 211, 41));
        pushButton_planTrip = new QPushButton(mainMenu);
        pushButton_planTrip->setObjectName(QStringLiteral("pushButton_planTrip"));
        pushButton_planTrip->setGeometry(QRect(190, 240, 211, 41));
        pushButton_tourAndPurchase = new QPushButton(mainMenu);
        pushButton_tourAndPurchase->setObjectName(QStringLiteral("pushButton_tourAndPurchase"));
        pushButton_tourAndPurchase->setGeometry(QRect(190, 290, 211, 41));
        pushButton_Quit = new QPushButton(mainMenu);
        pushButton_Quit->setObjectName(QStringLiteral("pushButton_Quit"));
        pushButton_Quit->setGeometry(QRect(190, 340, 211, 41));
        pushButton_Admin = new QPushButton(mainMenu);
        pushButton_Admin->setObjectName(QStringLiteral("pushButton_Admin"));
        pushButton_Admin->setGeometry(QRect(460, 400, 75, 23));
        label_mainTitle = new QLabel(mainMenu);
        label_mainTitle->setObjectName(QStringLiteral("label_mainTitle"));
        label_mainTitle->setGeometry(QRect(160, 20, 291, 141));
        adminViewCurrentWineWineries->addWidget(mainMenu);
        viewListOfWineries = new QWidget();
        viewListOfWineries->setObjectName(QStringLiteral("viewListOfWineries"));
        pushButton_back_viewList = new QPushButton(viewListOfWineries);
        pushButton_back_viewList->setObjectName(QStringLiteral("pushButton_back_viewList"));
        pushButton_back_viewList->setGeometry(QRect(210, 380, 75, 23));
        pushButton_viewCurrentList = new QPushButton(viewListOfWineries);
        pushButton_viewCurrentList->setObjectName(QStringLiteral("pushButton_viewCurrentList"));
        pushButton_viewCurrentList->setGeometry(QRect(160, 90, 271, 31));
        pushButton_viewWines = new QPushButton(viewListOfWineries);
        pushButton_viewWines->setObjectName(QStringLiteral("pushButton_viewWines"));
        pushButton_viewWines->setGeometry(QRect(160, 50, 271, 31));
        pushButton_3 = new QPushButton(viewListOfWineries);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(300, 380, 75, 23));
        pushButton_10 = new QPushButton(viewListOfWineries);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(160, 170, 271, 31));
        label_secondInViewList = new QLabel(viewListOfWineries);
        label_secondInViewList->setObjectName(QStringLiteral("label_secondInViewList"));
        label_secondInViewList->setGeometry(QRect(130, 250, 341, 101));
        label_ViewListTitle = new QLabel(viewListOfWineries);
        label_ViewListTitle->setObjectName(QStringLiteral("label_ViewListTitle"));
        label_ViewListTitle->setGeometry(QRect(50, 10, 511, 31));
        label_Excellence = new QLabel(viewListOfWineries);
        label_Excellence->setObjectName(QStringLiteral("label_Excellence"));
        label_Excellence->setGeometry(QRect(230, 210, 321, 21));
        pushButton_viewDistanceList = new QPushButton(viewListOfWineries);
        pushButton_viewDistanceList->setObjectName(QStringLiteral("pushButton_viewDistanceList"));
        pushButton_viewDistanceList->setGeometry(QRect(160, 130, 271, 31));
        adminViewCurrentWineWineries->addWidget(viewListOfWineries);
        viewDistances = new QWidget();
        viewDistances->setObjectName(QStringLiteral("viewDistances"));
        distanceTable = new QTableWidget(viewDistances);
        distanceTable->setObjectName(QStringLiteral("distanceTable"));
        distanceTable->setGeometry(QRect(10, 20, 591, 401));
        backButtonViewDistance = new QPushButton(viewDistances);
        backButtonViewDistance->setObjectName(QStringLiteral("backButtonViewDistance"));
        backButtonViewDistance->setGeometry(QRect(530, 430, 75, 23));
        adminViewCurrentWineWineries->addWidget(viewDistances);
        viewWines = new QWidget();
        viewWines->setObjectName(QStringLiteral("viewWines"));
        list_wineList = new QListWidget(viewWines);
        list_wineList->setObjectName(QStringLiteral("list_wineList"));
        list_wineList->setGeometry(QRect(240, 10, 271, 451));
        pushButton_backViewWines = new QPushButton(viewWines);
        pushButton_backViewWines->setObjectName(QStringLiteral("pushButton_backViewWines"));
        pushButton_backViewWines->setGeometry(QRect(40, 400, 75, 23));
        viewWines_2 = new QLabel(viewWines);
        viewWines_2->setObjectName(QStringLiteral("viewWines_2"));
        viewWines_2->setGeometry(QRect(30, 130, 181, 121));
        label_featuredWines = new QLabel(viewWines);
        label_featuredWines->setObjectName(QStringLiteral("label_featuredWines"));
        label_featuredWines->setGeometry(QRect(30, 30, 161, 51));
        adminViewCurrentWineWineries->addWidget(viewWines);
        page_AboutTheVilla = new QWidget();
        page_AboutTheVilla->setObjectName(QStringLiteral("page_AboutTheVilla"));
        label_AboutTheVilla = new QLabel(page_AboutTheVilla);
        label_AboutTheVilla->setObjectName(QStringLiteral("label_AboutTheVilla"));
        label_AboutTheVilla->setGeometry(QRect(30, 70, 231, 151));
        textBrowser = new QTextBrowser(page_AboutTheVilla);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(280, 70, 251, 171));
        pushButton_backAboutVilla = new QPushButton(page_AboutTheVilla);
        pushButton_backAboutVilla->setObjectName(QStringLiteral("pushButton_backAboutVilla"));
        pushButton_backAboutVilla->setGeometry(QRect(230, 390, 71, 23));
        label_AboutVilla2 = new QLabel(page_AboutTheVilla);
        label_AboutVilla2->setObjectName(QStringLiteral("label_AboutVilla2"));
        label_AboutVilla2->setGeometry(QRect(30, 250, 231, 101));
        label_AboutVilla3 = new QLabel(page_AboutTheVilla);
        label_AboutVilla3->setObjectName(QStringLiteral("label_AboutVilla3"));
        label_AboutVilla3->setGeometry(QRect(280, 250, 251, 101));
        label_AboutVIllaTItle = new QLabel(page_AboutTheVilla);
        label_AboutVIllaTItle->setObjectName(QStringLiteral("label_AboutVIllaTItle"));
        label_AboutVIllaTItle->setGeometry(QRect(180, 10, 381, 16));
        pushButton_website = new QPushButton(page_AboutTheVilla);
        pushButton_website->setObjectName(QStringLiteral("pushButton_website"));
        pushButton_website->setGeometry(QRect(310, 390, 75, 23));
        adminViewCurrentWineWineries->addWidget(page_AboutTheVilla);
        planATrip = new QWidget();
        planATrip->setObjectName(QStringLiteral("planATrip"));
        pushButton_backPlanTrip = new QPushButton(planATrip);
        pushButton_backPlanTrip->setObjectName(QStringLiteral("pushButton_backPlanTrip"));
        pushButton_backPlanTrip->setGeometry(QRect(20, 420, 75, 23));
        label_planATrip = new QLabel(planATrip);
        label_planATrip->setObjectName(QStringLiteral("label_planATrip"));
        label_planATrip->setGeometry(QRect(170, 10, 241, 121));
        pushButton_ = new QPushButton(planATrip);
        pushButton_->setObjectName(QStringLiteral("pushButton_"));
        pushButton_->setGeometry(QRect(170, 190, 251, 61));
        pushButton_shortestTrip = new QPushButton(planATrip);
        pushButton_shortestTrip->setObjectName(QStringLiteral("pushButton_shortestTrip"));
        pushButton_shortestTrip->setGeometry(QRect(170, 260, 251, 61));
        pushButton_visitAll = new QPushButton(planATrip);
        pushButton_visitAll->setObjectName(QStringLiteral("pushButton_visitAll"));
        pushButton_visitAll->setGeometry(QRect(170, 330, 251, 61));
        adminViewCurrentWineWineries->addWidget(planATrip);
        page_finalVisitAll = new QWidget();
        page_finalVisitAll->setObjectName(QStringLiteral("page_finalVisitAll"));
        list_visitAll = new QListWidget(page_finalVisitAll);
        list_visitAll->setObjectName(QStringLiteral("list_visitAll"));
        list_visitAll->setGeometry(QRect(10, 80, 471, 341));
        pushButton_16 = new QPushButton(page_finalVisitAll);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(490, 80, 111, 51));
        pushButton_17 = new QPushButton(page_finalVisitAll);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(500, 370, 101, 51));
        label_3 = new QLabel(page_finalVisitAll);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(40, 430, 241, 16));
        label_distance_VisitAll = new QLabel(page_finalVisitAll);
        label_distance_VisitAll->setObjectName(QStringLiteral("label_distance_VisitAll"));
        label_distance_VisitAll->setGeometry(QRect(310, 430, 191, 16));
        visitAllTitle = new QLabel(page_finalVisitAll);
        visitAllTitle->setObjectName(QStringLiteral("visitAllTitle"));
        visitAllTitle->setGeometry(QRect(20, 50, 411, 21));
        label_19 = new QLabel(page_finalVisitAll);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 10, 411, 31));
        adminViewCurrentWineWineries->addWidget(page_finalVisitAll);
        page_shortestTrip = new QWidget();
        page_shortestTrip->setObjectName(QStringLiteral("page_shortestTrip"));
        pushButton_5 = new QPushButton(page_shortestTrip);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(10, 420, 75, 23));
        lineEdit_numberOfWineries = new QLineEdit(page_shortestTrip);
        lineEdit_numberOfWineries->setObjectName(QStringLiteral("lineEdit_numberOfWineries"));
        lineEdit_numberOfWineries->setGeometry(QRect(160, 200, 291, 31));
        label_15 = new QLabel(page_shortestTrip);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(70, 200, 81, 20));
        pushButton_shortestTrip_next = new QPushButton(page_shortestTrip);
        pushButton_shortestTrip_next->setObjectName(QStringLiteral("pushButton_shortestTrip_next"));
        pushButton_shortestTrip_next->setGeometry(QRect(460, 200, 111, 31));
        label_promptForWineries = new QLabel(page_shortestTrip);
        label_promptForWineries->setObjectName(QStringLiteral("label_promptForWineries"));
        label_promptForWineries->setGeometry(QRect(40, 90, 571, 61));
        adminViewCurrentWineWineries->addWidget(page_shortestTrip);
        page_shortestTripPage2 = new QWidget();
        page_shortestTripPage2->setObjectName(QStringLiteral("page_shortestTripPage2"));
        pushButton_shortestTripPage2_back = new QPushButton(page_shortestTripPage2);
        pushButton_shortestTripPage2_back->setObjectName(QStringLiteral("pushButton_shortestTripPage2_back"));
        pushButton_shortestTripPage2_back->setGeometry(QRect(30, 420, 75, 23));
        list_customTripPage2 = new QListWidget(page_shortestTripPage2);
        list_customTripPage2->setObjectName(QStringLiteral("list_customTripPage2"));
        list_customTripPage2->setGeometry(QRect(30, 90, 411, 321));
        pushButton_9 = new QPushButton(page_shortestTripPage2);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(460, 230, 111, 31));
        title_1 = new QLabel(page_shortestTripPage2);
        title_1->setObjectName(QStringLiteral("title_1"));
        title_1->setGeometry(QRect(40, 40, 471, 31));
        adminViewCurrentWineWineries->addWidget(page_shortestTripPage2);
        page_shortestTripPage3 = new QWidget();
        page_shortestTripPage3->setObjectName(QStringLiteral("page_shortestTripPage3"));
        list_finalListShortestTrip = new QListWidget(page_shortestTripPage3);
        list_finalListShortestTrip->setObjectName(QStringLiteral("list_finalListShortestTrip"));
        list_finalListShortestTrip->setGeometry(QRect(0, 80, 431, 341));
        label_2 = new QLabel(page_shortestTripPage3);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 430, 321, 16));
        pushButton_6 = new QPushButton(page_shortestTripPage3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(450, 80, 121, 41));
        pushButton_15 = new QPushButton(page_shortestTripPage3);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(450, 130, 121, 41));
        label_17 = new QLabel(page_shortestTripPage3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 40, 401, 31));
        label_18 = new QLabel(page_shortestTripPage3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 10, 381, 31));
        distanceShortestTrip = new QLabel(page_shortestTripPage3);
        distanceShortestTrip->setObjectName(QStringLiteral("distanceShortestTrip"));
        distanceShortestTrip->setGeometry(QRect(340, 430, 171, 16));
        adminViewCurrentWineWineries->addWidget(page_shortestTripPage3);
        page_customTrip = new QWidget();
        page_customTrip->setObjectName(QStringLiteral("page_customTrip"));
        list_customTrip = new QListWidget(page_customTrip);
        list_customTrip->setObjectName(QStringLiteral("list_customTrip"));
        list_customTrip->setGeometry(QRect(20, 80, 581, 321));
        pushButton_next = new QPushButton(page_customTrip);
        pushButton_next->setObjectName(QStringLiteral("pushButton_next"));
        pushButton_next->setGeometry(QRect(530, 410, 75, 23));
        pushButton_customTrip_back = new QPushButton(page_customTrip);
        pushButton_customTrip_back->setObjectName(QStringLiteral("pushButton_customTrip_back"));
        pushButton_customTrip_back->setGeometry(QRect(20, 410, 75, 23));
        customTrip_title_1 = new QLabel(page_customTrip);
        customTrip_title_1->setObjectName(QStringLiteral("customTrip_title_1"));
        customTrip_title_1->setGeometry(QRect(130, 30, 311, 21));
        adminViewCurrentWineWineries->addWidget(page_customTrip);
        page_customTrip_final = new QWidget();
        page_customTrip_final->setObjectName(QStringLiteral("page_customTrip_final"));
        list_FinalListCustomTrip = new QListWidget(page_customTrip_final);
        list_FinalListCustomTrip->setObjectName(QStringLiteral("list_FinalListCustomTrip"));
        list_FinalListCustomTrip->setGeometry(QRect(10, 90, 421, 331));
        pushButton_shopForWines = new QPushButton(page_customTrip_final);
        pushButton_shopForWines->setObjectName(QStringLiteral("pushButton_shopForWines"));
        pushButton_shopForWines->setGeometry(QRect(460, 90, 101, 41));
        push_button_customTrip_Done = new QPushButton(page_customTrip_final);
        push_button_customTrip_Done->setObjectName(QStringLiteral("push_button_customTrip_Done"));
        push_button_customTrip_Done->setGeometry(QRect(460, 140, 101, 41));
        label_CustomTrip_Title = new QLabel(page_customTrip_final);
        label_CustomTrip_Title->setObjectName(QStringLiteral("label_CustomTrip_Title"));
        label_CustomTrip_Title->setGeometry(QRect(10, 50, 421, 41));
        label_16 = new QLabel(page_customTrip_final);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 430, 341, 21));
        thankYou = new QLabel(page_customTrip_final);
        thankYou->setObjectName(QStringLiteral("thankYou"));
        thankYou->setGeometry(QRect(10, 20, 351, 31));
        distanceCustomFinal = new QLabel(page_customTrip_final);
        distanceCustomFinal->setObjectName(QStringLiteral("distanceCustomFinal"));
        distanceCustomFinal->setGeometry(QRect(360, 430, 141, 21));
        adminViewCurrentWineWineries->addWidget(page_customTrip_final);
        tourWineriesAndPurchase = new QWidget();
        tourWineriesAndPurchase->setObjectName(QStringLiteral("tourWineriesAndPurchase"));
        pushButton_backTourAndPurchase = new QPushButton(tourWineriesAndPurchase);
        pushButton_backTourAndPurchase->setObjectName(QStringLiteral("pushButton_backTourAndPurchase"));
        pushButton_backTourAndPurchase->setGeometry(QRect(20, 410, 75, 23));
        pushButton = new QPushButton(tourWineriesAndPurchase);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(190, 170, 251, 71));
        pushButton_2 = new QPushButton(tourWineriesAndPurchase);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(190, 260, 251, 71));
        label_20 = new QLabel(tourWineriesAndPurchase);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(160, 30, 311, 111));
        adminViewCurrentWineWineries->addWidget(tourWineriesAndPurchase);
        adminLogin = new QWidget();
        adminLogin->setObjectName(QStringLiteral("adminLogin"));
        lineEdit_username = new QLineEdit(adminLogin);
        lineEdit_username->setObjectName(QStringLiteral("lineEdit_username"));
        lineEdit_username->setGeometry(QRect(230, 210, 161, 20));
        lineEdit_password = new QLineEdit(adminLogin);
        lineEdit_password->setObjectName(QStringLiteral("lineEdit_password"));
        lineEdit_password->setGeometry(QRect(230, 250, 161, 21));
        lineEdit_password->setEchoMode(QLineEdit::Password);
        label_5 = new QLabel(adminLogin);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(154, 210, 61, 16));
        label_6 = new QLabel(adminLogin);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(154, 250, 51, 20));
        pushButton_8 = new QPushButton(adminLogin);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(30, 380, 75, 23));
        pushButton_adminLogin = new QPushButton(adminLogin);
        pushButton_adminLogin->setObjectName(QStringLiteral("pushButton_adminLogin"));
        pushButton_adminLogin->setGeometry(QRect(220, 300, 171, 23));
        label_AdminLogin = new QLabel(adminLogin);
        label_AdminLogin->setObjectName(QStringLiteral("label_AdminLogin"));
        label_AdminLogin->setGeometry(QRect(150, 30, 291, 141));
        adminViewCurrentWineWineries->addWidget(adminLogin);
        afterAdminLogin = new QWidget();
        afterAdminLogin->setObjectName(QStringLiteral("afterAdminLogin"));
        pushButton_adminLogout = new QPushButton(afterAdminLogin);
        pushButton_adminLogout->setObjectName(QStringLiteral("pushButton_adminLogout"));
        pushButton_adminLogout->setGeometry(QRect(30, 390, 75, 23));
        label_8 = new QLabel(afterAdminLogin);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(170, 120, 171, 71));
        pushButton_4 = new QPushButton(afterAdminLogin);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(160, 160, 281, 61));
        pushButton_modifyWine = new QPushButton(afterAdminLogin);
        pushButton_modifyWine->setObjectName(QStringLiteral("pushButton_modifyWine"));
        pushButton_modifyWine->setGeometry(QRect(160, 230, 281, 61));
        label_titleAdminFunctions = new QLabel(afterAdminLogin);
        label_titleAdminFunctions->setObjectName(QStringLiteral("label_titleAdminFunctions"));
        label_titleAdminFunctions->setGeometry(QRect(150, 20, 301, 111));
        pushButton_14 = new QPushButton(afterAdminLogin);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(160, 300, 281, 61));
        adminViewCurrentWineWineries->addWidget(afterAdminLogin);
        page_addWineryInAdmin = new QWidget();
        page_addWineryInAdmin->setObjectName(QStringLiteral("page_addWineryInAdmin"));
        pushButton_viewCurrentLists_addWinery = new QPushButton(page_addWineryInAdmin);
        pushButton_viewCurrentLists_addWinery->setObjectName(QStringLiteral("pushButton_viewCurrentLists_addWinery"));
        pushButton_viewCurrentLists_addWinery->setGeometry(QRect(180, 310, 261, 51));
        label_CVLogoAdmin = new QLabel(page_addWineryInAdmin);
        label_CVLogoAdmin->setObjectName(QStringLiteral("label_CVLogoAdmin"));
        label_CVLogoAdmin->setGeometry(QRect(160, 20, 311, 131));
        label_Add_winery_title = new QLabel(page_addWineryInAdmin);
        label_Add_winery_title->setObjectName(QStringLiteral("label_Add_winery_title"));
        label_Add_winery_title->setGeometry(QRect(230, 170, 341, 31));
        pushButton_11 = new QPushButton(page_addWineryInAdmin);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(180, 220, 261, 51));
        pushButton_backAddWinery = new QPushButton(page_addWineryInAdmin);
        pushButton_backAddWinery->setObjectName(QStringLiteral("pushButton_backAddWinery"));
        pushButton_backAddWinery->setGeometry(QRect(30, 400, 75, 23));
        adminViewCurrentWineWineries->addWidget(page_addWineryInAdmin);
        page_addWineryPage = new QWidget();
        page_addWineryPage->setObjectName(QStringLiteral("page_addWineryPage"));
        addWineryOK = new QPushButton(page_addWineryPage);
        addWineryOK->setObjectName(QStringLiteral("addWineryOK"));
        addWineryOK->setGeometry(QRect(370, 420, 75, 23));
        addWineryCancel = new QPushButton(page_addWineryPage);
        addWineryCancel->setObjectName(QStringLiteral("addWineryCancel"));
        addWineryCancel->setGeometry(QRect(480, 420, 75, 23));
        adminViewCurrentWineWineries->addWidget(page_addWineryPage);
        page_AdminListVIew = new QWidget();
        page_AdminListVIew->setObjectName(QStringLiteral("page_AdminListVIew"));
        listWidget_adminViewWIne = new QListWidget(page_AdminListVIew);
        listWidget_adminViewWIne->setObjectName(QStringLiteral("listWidget_adminViewWIne"));
        listWidget_adminViewWIne->setGeometry(QRect(20, 20, 271, 391));
        listWidget_adminViewWineries = new QListWidget(page_AdminListVIew);
        listWidget_adminViewWineries->setObjectName(QStringLiteral("listWidget_adminViewWineries"));
        listWidget_adminViewWineries->setGeometry(QRect(320, 20, 261, 391));
        pushButton_backInAdminList = new QPushButton(page_AdminListVIew);
        pushButton_backInAdminList->setObjectName(QStringLiteral("pushButton_backInAdminList"));
        pushButton_backInAdminList->setGeometry(QRect(20, 420, 75, 23));
        adminViewCurrentWineWineries->addWidget(page_AdminListVIew);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        adminViewCurrentWineWineries->addWidget(page_4);
        page_ViewCurrentLists = new QWidget();
        page_ViewCurrentLists->setObjectName(QStringLiteral("page_ViewCurrentLists"));
        list_currentWines = new QListWidget(page_ViewCurrentLists);
        list_currentWines->setObjectName(QStringLiteral("list_currentWines"));
        list_currentWines->setGeometry(QRect(20, 100, 271, 321));
        list_currentWineries = new QListWidget(page_ViewCurrentLists);
        list_currentWineries->setObjectName(QStringLiteral("list_currentWineries"));
        list_currentWineries->setGeometry(QRect(300, 100, 291, 321));
        label = new QLabel(page_ViewCurrentLists);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(100, 50, 101, 41));
        label_4 = new QLabel(page_ViewCurrentLists);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(400, 70, 61, 20));
        pushButton_backViewCurrentLists = new QPushButton(page_ViewCurrentLists);
        pushButton_backViewCurrentLists->setObjectName(QStringLiteral("pushButton_backViewCurrentLists"));
        pushButton_backViewCurrentLists->setGeometry(QRect(20, 430, 131, 23));
        adminViewCurrentWineWineries->addWidget(page_ViewCurrentLists);
        viewCurrentList_childOViewList = new QWidget();
        viewCurrentList_childOViewList->setObjectName(QStringLiteral("viewCurrentList_childOViewList"));
        pushButton_backInListView = new QPushButton(viewCurrentList_childOViewList);
        pushButton_backInListView->setObjectName(QStringLiteral("pushButton_backInListView"));
        pushButton_backInListView->setGeometry(QRect(340, 420, 75, 23));
        wineryList = new QListWidget(viewCurrentList_childOViewList);
        wineryList->setObjectName(QStringLiteral("wineryList"));
        wineryList->setGeometry(QRect(230, 10, 291, 401));
        label_temp = new QLabel(viewCurrentList_childOViewList);
        label_temp->setObjectName(QStringLiteral("label_temp"));
        label_temp->setGeometry(QRect(20, 50, 191, 91));
        label_picture = new QLabel(viewCurrentList_childOViewList);
        label_picture->setObjectName(QStringLiteral("label_picture"));
        label_picture->setGeometry(QRect(20, 170, 171, 131));
        adminViewCurrentWineWineries->addWidget(viewCurrentList_childOViewList);
        page_wineOptionsAdmin = new QWidget();
        page_wineOptionsAdmin->setObjectName(QStringLiteral("page_wineOptionsAdmin"));
        label_CVLogoAdmin_2 = new QLabel(page_wineOptionsAdmin);
        label_CVLogoAdmin_2->setObjectName(QStringLiteral("label_CVLogoAdmin_2"));
        label_CVLogoAdmin_2->setGeometry(QRect(130, 10, 341, 131));
        pushButton_back_wineOptions = new QPushButton(page_wineOptionsAdmin);
        pushButton_back_wineOptions->setObjectName(QStringLiteral("pushButton_back_wineOptions"));
        pushButton_back_wineOptions->setGeometry(QRect(30, 410, 75, 23));
        frame_6 = new QFrame(page_wineOptionsAdmin);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(120, 170, 361, 211));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Sunken);
        label_wineOptions = new QLabel(frame_6);
        label_wineOptions->setObjectName(QStringLiteral("label_wineOptions"));
        label_wineOptions->setGeometry(QRect(50, 20, 91, 21));
        pushButton_addWine_wineOptions = new QPushButton(frame_6);
        pushButton_addWine_wineOptions->setObjectName(QStringLiteral("pushButton_addWine_wineOptions"));
        pushButton_addWine_wineOptions->setGeometry(QRect(50, 70, 261, 51));
        pushButton_editWine_wineOptions = new QPushButton(frame_6);
        pushButton_editWine_wineOptions->setObjectName(QStringLiteral("pushButton_editWine_wineOptions"));
        pushButton_editWine_wineOptions->setGeometry(QRect(50, 140, 261, 51));
        adminViewCurrentWineWineries->addWidget(page_wineOptionsAdmin);
        frame_6->raise();
        label_CVLogoAdmin_2->raise();
        pushButton_back_wineOptions->raise();
        page_addWine_wineOptionsAdmin = new QWidget();
        page_addWine_wineOptionsAdmin->setObjectName(QStringLiteral("page_addWine_wineOptionsAdmin"));
        frame = new QFrame(page_addWine_wineOptionsAdmin);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(20, 20, 231, 71));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Sunken);
        comboBox_selectWinery_addWine = new QComboBox(frame);
        comboBox_selectWinery_addWine->setObjectName(QStringLiteral("comboBox_selectWinery_addWine"));
        comboBox_selectWinery_addWine->setGeometry(QRect(10, 40, 201, 22));
        label_10 = new QLabel(frame);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 10, 91, 16));
        frame_2 = new QFrame(page_addWine_wineOptionsAdmin);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(20, 100, 231, 321));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Sunken);
        label_9 = new QLabel(frame_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 10, 81, 16));
        textBrowser_viewCurrent_addWine = new QTextBrowser(frame_2);
        textBrowser_viewCurrent_addWine->setObjectName(QStringLiteral("textBrowser_viewCurrent_addWine"));
        textBrowser_viewCurrent_addWine->setGeometry(QRect(10, 40, 211, 271));
        frame_3 = new QFrame(page_addWine_wineOptionsAdmin);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(270, 20, 301, 401));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Sunken);
        label_11 = new QLabel(frame_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 10, 111, 16));
        label_12 = new QLabel(frame_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 70, 71, 16));
        label_13 = new QLabel(frame_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 150, 61, 16));
        label_14 = new QLabel(frame_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 230, 61, 16));
        lineEdit_wineName_addWine = new QLineEdit(frame_3);
        lineEdit_wineName_addWine->setObjectName(QStringLiteral("lineEdit_wineName_addWine"));
        lineEdit_wineName_addWine->setGeometry(QRect(100, 70, 181, 20));
        lineEdit_wineYear_addWine = new QLineEdit(frame_3);
        lineEdit_wineYear_addWine->setObjectName(QStringLiteral("lineEdit_wineYear_addWine"));
        lineEdit_wineYear_addWine->setGeometry(QRect(100, 150, 181, 20));
        lineEdit_winePrice_addWine = new QLineEdit(frame_3);
        lineEdit_winePrice_addWine->setObjectName(QStringLiteral("lineEdit_winePrice_addWine"));
        lineEdit_winePrice_addWine->setGeometry(QRect(100, 230, 181, 20));
        pushButton_confirmAdd_addWine = new QPushButton(frame_3);
        pushButton_confirmAdd_addWine->setObjectName(QStringLiteral("pushButton_confirmAdd_addWine"));
        pushButton_confirmAdd_addWine->setGeometry(QRect(80, 322, 141, 41));
        pushButton_back_addWine = new QPushButton(page_addWine_wineOptionsAdmin);
        pushButton_back_addWine->setObjectName(QStringLiteral("pushButton_back_addWine"));
        pushButton_back_addWine->setGeometry(QRect(20, 430, 75, 23));
        adminViewCurrentWineWineries->addWidget(page_addWine_wineOptionsAdmin);
        page_editWine_wineOptionsAdmin = new QWidget();
        page_editWine_wineOptionsAdmin->setObjectName(QStringLiteral("page_editWine_wineOptionsAdmin"));
        pushButton__back_editWine = new QPushButton(page_editWine_wineOptionsAdmin);
        pushButton__back_editWine->setObjectName(QStringLiteral("pushButton__back_editWine"));
        pushButton__back_editWine->setGeometry(QRect(20, 420, 75, 23));
        pushButton_apply_editWine = new QPushButton(page_editWine_wineOptionsAdmin);
        pushButton_apply_editWine->setObjectName(QStringLiteral("pushButton_apply_editWine"));
        pushButton_apply_editWine->setGeometry(QRect(474, 420, 91, 23));
        frame_4 = new QFrame(page_editWine_wineOptionsAdmin);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(10, 10, 571, 81));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Sunken);
        comboBox_selectWinery_editWine = new QComboBox(frame_4);
        comboBox_selectWinery_editWine->setObjectName(QStringLiteral("comboBox_selectWinery_editWine"));
        comboBox_selectWinery_editWine->setGeometry(QRect(20, 40, 211, 22));
        label_selectWinery_editWine = new QLabel(frame_4);
        label_selectWinery_editWine->setObjectName(QStringLiteral("label_selectWinery_editWine"));
        label_selectWinery_editWine->setGeometry(QRect(20, 10, 91, 16));
        frame_5 = new QFrame(page_editWine_wineOptionsAdmin);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(10, 100, 571, 311));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Sunken);
        label_tableEdit_editWine = new QLabel(frame_5);
        label_tableEdit_editWine->setObjectName(QStringLiteral("label_tableEdit_editWine"));
        label_tableEdit_editWine->setGeometry(QRect(20, 10, 121, 16));
        tableWidget_editWine = new QTableWidget(frame_5);
        tableWidget_editWine->setObjectName(QStringLiteral("tableWidget_editWine"));
        tableWidget_editWine->setGeometry(QRect(20, 40, 531, 251));
        tableWidget_editWine->setFrameShadow(QFrame::Raised);
        tableWidget_editWine->setAlternatingRowColors(true);
        tableWidget_editWine->setColumnCount(0);
        adminViewCurrentWineWineries->addWidget(page_editWine_wineOptionsAdmin);
        frame_5->raise();
        frame_4->raise();
        pushButton__back_editWine->raise();
        pushButton_apply_editWine->raise();
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 634, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        adminViewCurrentWineWineries->setCurrentIndex(22);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        push_button_viewListOfWineries->setText(QApplication::translate("MainWindow", "View Wineries and Wines", 0));
        pushButton_planTrip->setText(QApplication::translate("MainWindow", "Plan a Day Trip", 0));
        pushButton_tourAndPurchase->setText(QApplication::translate("MainWindow", "Tour Wineries and Purchase", 0));
        pushButton_Quit->setText(QApplication::translate("MainWindow", "Quit", 0));
        pushButton_Admin->setText(QApplication::translate("MainWindow", "Admin Login", 0));
        label_mainTitle->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pushButton_back_viewList->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_viewCurrentList->setText(QApplication::translate("MainWindow", "View Wineries", 0));
        pushButton_viewWines->setText(QApplication::translate("MainWindow", "View Wines", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Home", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "About the Canyon Villa", 0));
        label_secondInViewList->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_ViewListTitle->setText(QApplication::translate("MainWindow", "View featured Wineries in the Canyon Villa Tour Program", 0));
        label_Excellence->setText(QApplication::translate("MainWindow", "Founded in 1905", 0));
        pushButton_viewDistanceList->setText(QApplication::translate("MainWindow", "View Distances", 0));
        backButtonViewDistance->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_backViewWines->setText(QApplication::translate("MainWindow", "Back", 0));
        viewWines_2->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_featuredWines->setText(QApplication::translate("MainWindow", "Featured Wines", 0));
        label_AboutTheVilla->setText(QString());
        textBrowser->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The Canyon Villa was founded in 1965 and is located in Rutherford California, USA.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">The winery sits on a portion of the histroic Napa Valley acquired by Franch wine enthusiast Gustav Bernard. The Canyon Villa prides itself in exceptional hospitallity </span></p></body></html>", 0));
        pushButton_backAboutVilla->setText(QApplication::translate("MainWindow", "Back", 0));
        label_AboutVilla2->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_AboutVilla3->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_AboutVIllaTItle->setText(QApplication::translate("MainWindow", "About the Canyon Villa", 0));
        pushButton_website->setText(QApplication::translate("MainWindow", "View Website", 0));
        pushButton_backPlanTrip->setText(QApplication::translate("MainWindow", "Back", 0));
        label_planATrip->setText(QApplication::translate("MainWindow", "                         Plan a Trip Interface", 0));
        pushButton_->setText(QApplication::translate("MainWindow", "Custom Trip", 0));
        pushButton_shortestTrip->setText(QApplication::translate("MainWindow", "Shortest Trip", 0));
        pushButton_visitAll->setText(QApplication::translate("MainWindow", "Visit All", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "Shop for Wines", 0));
        pushButton_17->setText(QApplication::translate("MainWindow", "Done", 0));
        label_3->setText(QApplication::translate("MainWindow", "Distance Traveled In Miles: ", 0));
        label_distance_VisitAll->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        visitAllTitle->setText(QApplication::translate("MainWindow", "You visited All of the Wineries!", 0));
        label_19->setText(QApplication::translate("MainWindow", "Thank You!", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "Back", 0));
        lineEdit_numberOfWineries->setText(QString());
        label_15->setText(QApplication::translate("MainWindow", "# of Wineries:", 0));
        pushButton_shortestTrip_next->setText(QApplication::translate("MainWindow", "Next", 0));
        label_promptForWineries->setText(QApplication::translate("MainWindow", "Please enter the number of wineries you would like to visit", 0));
        pushButton_shortestTripPage2_back->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_9->setText(QApplication::translate("MainWindow", "Next", 0));
        title_1->setText(QApplication::translate("MainWindow", "Select the Winery Where you would like to begin", 0));
        label_2->setText(QApplication::translate("MainWindow", "Total Distance Traveled in Miles: ", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "Shop for wines", 0));
        pushButton_15->setText(QApplication::translate("MainWindow", "Done", 0));
        label_17->setText(QApplication::translate("MainWindow", "List of Wineries you visited", 0));
        label_18->setText(QApplication::translate("MainWindow", "Thank you for taking a trip!", 0));
        distanceShortestTrip->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pushButton_next->setText(QApplication::translate("MainWindow", "Next", 0));
        pushButton_customTrip_back->setText(QApplication::translate("MainWindow", "Back", 0));
        customTrip_title_1->setText(QApplication::translate("MainWindow", "Select Wineries You would like to visit", 0));
        pushButton_shopForWines->setText(QApplication::translate("MainWindow", "Shop for Wines", 0));
        push_button_customTrip_Done->setText(QApplication::translate("MainWindow", "Done", 0));
        label_CustomTrip_Title->setText(QApplication::translate("MainWindow", "List of Wineries you visited", 0));
        label_16->setText(QApplication::translate("MainWindow", "Total Distance Traveled in Miles: ", 0));
        thankYou->setText(QApplication::translate("MainWindow", "Thank You for planning a Trip!", 0));
        distanceCustomFinal->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pushButton_backTourAndPurchase->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Tour Wineries", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "Shopping Cart", 0));
        label_20->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        lineEdit_username->setText(QString());
        lineEdit_password->setText(QString());
        label_5->setText(QApplication::translate("MainWindow", "Username", 0));
        label_6->setText(QApplication::translate("MainWindow", "Password", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_adminLogin->setText(QApplication::translate("MainWindow", "Login", 0));
        label_AdminLogin->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pushButton_adminLogout->setText(QApplication::translate("MainWindow", "Logout", 0));
        label_8->setText(QString());
        pushButton_4->setText(QApplication::translate("MainWindow", "Add A Winery", 0));
        pushButton_modifyWine->setText(QApplication::translate("MainWindow", "Add or Modify Wine", 0));
        label_titleAdminFunctions->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pushButton_14->setText(QApplication::translate("MainWindow", "View Current Wine and Winery Lists", 0));
        pushButton_viewCurrentLists_addWinery->setText(QApplication::translate("MainWindow", "View Current Lists", 0));
        label_CVLogoAdmin->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_Add_winery_title->setText(QApplication::translate("MainWindow", "Add a Winery", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "Add a Winery", 0));
        pushButton_backAddWinery->setText(QApplication::translate("MainWindow", "Back", 0));
        addWineryOK->setText(QApplication::translate("MainWindow", "OK", 0));
        addWineryCancel->setText(QApplication::translate("MainWindow", "Cancel", 0));
        pushButton_backInAdminList->setText(QApplication::translate("MainWindow", "Back", 0));
        label->setText(QApplication::translate("MainWindow", "All Wine Products", 0));
        label_4->setText(QApplication::translate("MainWindow", "All Wineries", 0));
        pushButton_backViewCurrentLists->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_backInListView->setText(QApplication::translate("MainWindow", "Back", 0));
        label_temp->setText(QApplication::translate("MainWindow", "Featured Wineries", 0));
        label_picture->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_CVLogoAdmin_2->setText(QApplication::translate("MainWindow", "logo label", 0));
        pushButton_back_wineOptions->setText(QApplication::translate("MainWindow", "Back", 0));
        label_wineOptions->setText(QApplication::translate("MainWindow", "Select an option:", 0));
        pushButton_addWine_wineOptions->setText(QApplication::translate("MainWindow", "Add a Wine", 0));
        pushButton_editWine_wineOptions->setText(QApplication::translate("MainWindow", "Edit a Wine", 0));
        label_10->setText(QApplication::translate("MainWindow", "Select Winery:", 0));
        label_9->setText(QApplication::translate("MainWindow", "Current Wines:", 0));
        label_11->setText(QApplication::translate("MainWindow", "Add a Wine Below:", 0));
        label_12->setText(QApplication::translate("MainWindow", "Wine Name:", 0));
        label_13->setText(QApplication::translate("MainWindow", "Wine Year:", 0));
        label_14->setText(QApplication::translate("MainWindow", "Wine Price:", 0));
        pushButton_confirmAdd_addWine->setText(QApplication::translate("MainWindow", "Add Wine", 0));
        pushButton_back_addWine->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton__back_editWine->setText(QApplication::translate("MainWindow", "Back", 0));
        pushButton_apply_editWine->setText(QApplication::translate("MainWindow", "Apply Changes", 0));
        label_selectWinery_editWine->setText(QApplication::translate("MainWindow", "Select Winery:", 0));
        label_tableEdit_editWine->setText(QApplication::translate("MainWindow", "Edit Wines Below:", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
